HA-24 Add GithubWebhook.
PieselBois/HaroldAdviser pull request #18
Opened 2018-05-01 20:52 UTC by weeellz

2018-05-01 21:18 UTC, fexolm requested changes

2018-05-01 21:18 UTC, fexolm commented on HaroldAdviser/Controllers/PipelineController.cs
> +            //TODO: handle github webhook to create pipeline
Please remove comment

2018-05-01 21:18 UTC, fexolm commented on HaroldAdviser/Controllers/UserController.cs
> +        public IActionResult GetWarnings()
Warnings are warnings, not strings.

2018-05-01 21:18 UTC, fexolm commented on HaroldAdviser/Controllers/UserController.cs
> +        public IActionResult GetWarnings()
Please add at least 6 warnings with long strings. You could use that json to get them.
``` [/home/fexolm/git/SLama/src/block.c:13]: (portability) 'mem' is of type 'void *'. When using void pointers in calculations, the behaviour is undefined.
[/home/fexolm/git/SLama/tests/block-test.c:15] -> [/home/fexolm/git/SLama/tests/block-test.c:16]: (style) Variable 'block' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/block-test.c:30] -> [/home/fexolm/git/SLama/tests/block-test.c:33]: (style) Variable 'block' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/block-test.c:31] -> [/home/fexolm/git/SLama/tests/block-test.c:35]: (style) Variable 'block2' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/block-test.c:55] -> [/home/fexolm/git/SLama/tests/block-test.c:58]: (style) Variable 'block' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/block-test.c:79] -> [/home/fexolm/git/SLama/tests/block-test.c:82]: (style) Variable 'block' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/block-test.c:80] -> [/home/fexolm/git/SLama/tests/block-test.c:83]: (style) Variable 'block2' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/matrix-base-algo-test.c:16] -> [/home/fexolm/git/SLama/tests/matrix-base-algo-test.c:20]: (style) Variable 'matrix' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/matrix-base-algo-test.c:17] -> [/home/fexolm/git/SLama/tests/matrix-base-algo-test.c:21]: (style) Variable 'matrix1' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/matrix-base-algo-test.c:51] -> [/home/fexolm/git/SLama/tests/matrix-base-algo-test.c:55]: (style) Variable 'matrix' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/matrix-base-algo-test.c:52] -> [/home/fexolm/git/SLama/tests/matrix-base-algo-test.c:56]: (style) Variable 'matrix1' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/matrix-base-algo-test.c:86] -> [/home/fexolm/git/SLama/tests/matrix-base-algo-test.c:87]: (style) Variable 'matrix' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/matmul-test.c:15] -> [/home/fexolm/git/SLama/tests/matmul-test.c:19]: (style) Variable 'matrix1' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/matmul-test.c:16] -> [/home/fexolm/git/SLama/tests/matmul-test.c:20]: (style) Variable 'matrix2' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/matmul-test.c:17] -> [/home/fexolm/git/SLama/tests/matmul-test.c:56]: (style) Variable 'result' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/base-matrix-test.c:15] -> [/home/fexolm/git/SLama/tests/base-matrix-test.c:16]: (style) Variable 'matrix' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/base-matrix-test.c:27] -> [/home/fexolm/git/SLama/tests/base-matrix-test.c:29]: (style) Variable 'matrix' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/base-matrix-test.c:28] -> [/home/fexolm/git/SLama/tests/base-matrix-test.c:35]: (style) Variable 'matrix1' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/base-matrix-test.c:46] -> [/home/fexolm/git/SLama/tests/base-matrix-test.c:48]: (style) Variable 'matrix' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/base-matrix-test.c:47] -> [/home/fexolm/git/SLama/tests/base-matrix-test.c:49]: (style) Variable 'matrix1' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/base-matrix-test.c:65] -> [/home/fexolm/git/SLama/tests/base-matrix-test.c:66]: (style) Variable 'matrix' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/base-matrix-test.c:83] -> [/home/fexolm/git/SLama/tests/base-matrix-test.c:86]: (style) Variable 'matrix' is reassigned a value before the old one has been used.
[/home/fexolm/git/SLama/tests/base-matrix-test.c:84] -> [/home/fexolm/git/SLama/tests/base-matrix-test.c:90]: (style) Variable 'matrix1' is reassigned a value before the old one has been used.
(information) Cppcheck cannot find all the include files (use --check-config for details)

2018-05-01 21:32 UTC, weeellz commented on HaroldAdviser/Controllers/PipelineController.cs
> +            //TODO: handle github webhook to create pipeline
done

2018-05-01 21:33 UTC, weeellz commented on HaroldAdviser/Controllers/UserController.cs
> +        public IActionResult GetWarnings()
done

2018-05-02 10:57 UTC, fexolm requested changes

2018-05-02 10:57 UTC, fexolm commented on HaroldAdviser/Views/User/AllRepositories.cshtml
> +    @*<script src="~/Scripts/get-warnings.js"></script>*@
Please remove comment. Also, this script is for repository view page. Please move it here.

2018-05-02 10:57 UTC, fexolm commented on HaroldAdviser/wwwroot/Scripts/get-warnings.js
> +                    $("").append(val.kind + val.file + val.lines + val.message);
Please add this class in repository view page.

2018-05-02 19:14 UTC, weeellz commented on HaroldAdviser/Views/User/AllRepositories.cshtml
> +    @*<script src="~/Scripts/get-warnings.js"></script>*@
done

2018-05-02 19:14 UTC, weeellz commented on HaroldAdviser/wwwroot/Scripts/get-warnings.js
> +                    $("").append(val.kind + val.file + val.lines + val.message);
done

2018-05-02 20:26 UTC, fexolm approved these changes

2018-05-02 20:26 UTC, merged