HA-14 Add methods to create and drop instance
PieselBois/HaroldAdviser pull request #8
Opened 2018-04-20 14:57 UTC by weeellz

2018-04-22 20:05 UTC, fexolm requested changes

2018-04-22 20:05 UTC, fexolm commented on HaroldAdviser/Controllers/UserController.cs
> +            var credential = Task.Run(GoogleCredential.GetApplicationDefaultAsync).Result;
please change .Result to async/await syntax
also remove Task.Run (method is already async)

2018-04-22 20:05 UTC, fexolm commented on HaroldAdviser/Controllers/UserController.cs
> +        public static GoogleCredential GetCredential()
Do you really need it public?

2018-04-22 20:05 UTC, fexolm commented on HaroldAdviser/Controllers/UserController.cs
> +        public static GoogleCredential GetCredential()
(Same with other methods)

2018-04-22 20:05 UTC, fexolm commented on HaroldAdviser/Controllers/UserController.cs
> -﻿using HaroldAdviser.Data;
I think we should create BL project.
Create google cloud instance is not really controller job.

2018-04-22 20:05 UTC, fexolm commented on HaroldAdviser/Controllers/UserController.cs
> -﻿using HaroldAdviser.Data;
But maybe we should create issue for it, and fix it later

2018-04-22 20:05 UTC, fexolm commented on HaroldAdviser/Controllers/UserController.cs
> +                ApplicationName = "Google-ComputeSample/0.1",
Please remove hardcoded strings and move them to project settings (or env vars if they shoult not store in github)

2018-04-22 20:05 UTC, fexolm commented on HaroldAdviser/Controllers/UserController.cs
> +            // To execute asynchronously in an async method, replace `request.Execute()` as shown:
Please use async operations

2018-04-22 20:05 UTC, fexolm commented on HaroldAdviser/Controllers/UserController.cs
> +            // To execute asynchronously in an async method, replace `request.Execute()` as shown:
Also, remove comments

2018-04-22 20:05 UTC, fexolm commented on HaroldAdviser/Controllers/UserController.cs
> +            InstancesResource.StopRequest requestStop = computeService.Instances.Stop(project, zone, instance);
Do u really need fully qualified name there?

2018-04-24 18:12 UTC, weeellz commented on HaroldAdviser/Controllers/UserController.cs
> +            InstancesResource.StopRequest requestStop = computeService.Instances.Stop(project, zone, instance);
done

2018-04-24 18:14 UTC, weeellz commented on HaroldAdviser/Controllers/UserController.cs
> +            // To execute asynchronously in an async method, replace `request.Execute()` as shown:
done

2018-04-24 18:14 UTC, weeellz commented on HaroldAdviser/Controllers/UserController.cs
> +            var credential = Task.Run(GoogleCredential.GetApplicationDefaultAsync).Result;
done

2018-04-24 18:21 UTC, weeellz commented on HaroldAdviser/Controllers/UserController.cs
> +        public static GoogleCredential GetCredential()
done

2018-04-24 18:33 UTC, fexolm commented on HaroldAdviser/Controllers/UserController.cs
> +            var credential = Task.Run(GoogleCredential.GetApplicationDefaultAsync).Result;
@weeellz Have you tried 
`var credential = await GoogleCredential.GetApplicationDefaultAsync();` ?

2018-04-24 18:39 UTC, weeellz commented on HaroldAdviser/Controllers/UserController.cs
> +            var credential = Task.Run(GoogleCredential.GetApplicationDefaultAsync).Result;
k m8

2018-04-24 20:04 UTC, fexolm requested changes

2018-04-24 20:04 UTC, fexolm commented on HaroldAdviser/Controllers/UserController.cs
> +        protected async void CreateInstance()
async Task maybe?

2018-04-24 20:04 UTC, fexolm commented on HaroldAdviser/Controllers/UserController.cs
> +        protected async void DropInstance()
Task?

2018-04-24 20:39 UTC, weeellz commented on HaroldAdviser/Controllers/UserController.cs
> +        protected async void CreateInstance()
done

2018-04-24 20:39 UTC, weeellz commented on HaroldAdviser/Controllers/UserController.cs
> +        protected async void DropInstance()
done

2018-04-24 20:40 UTC, weeellz commented on HaroldAdviser/Controllers/UserController.cs
> +                ApplicationName = "Google-ComputeSample/0.1",
done

2018-04-25 05:42 UTC, fexolm requested changes
Its ok, but please remove last hardcoded strings.
Also, it would be nice to add some logging here. But maybe it would be another issue.

2018-04-26 17:22 UTC, fexolm approved these changes

2018-04-26 17:22 UTC, merged